import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
// Components
import SideNavigation from "@/components/common/navigation/SideNavigation";
// Shadcn UI
import { Toaster } from "@/components/ui/toaster";
// 전역 CSS
import "@/styles/globals.css";

const NOTO_SANS_KR = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Shadcn UI - Todoboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={NOTO_SANS_KR.className}>
                <SideNavigation />
                {children}
                <Toaster />
            </body>
        </html>
    );
}
